version: '3.4'

services:
  sql:
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"

  justchat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=8080
      - ConnectionStrings__CommandDbConnection=Server=sql;Database=JustChatCommandDb;User=sa;Password=Your_password123;
    ports:
      - "8080:80"
